### PR TITLE
Fetch data from opendata.swiss

### PR DESCRIPTION
**Pull request by loleg**
Addresses #6 with a new `make fetch` command, which:

- downloads the latest [boundaries open data](https://opendata.swiss/en/dataset/swissboundaries3d-landesgrenzen)
- downloads the latest [height model open data](https://opendata.swiss/en/dataset/das-digitale-hohenmodell-der-schweiz-mit-einer-maschenweite-von-200-m)

I'm not sure where to get the [VEC200 files](https://github.com/interactivethings/swiss-maps/tree/master/src/V200) from, so for now we're just recycling the 2015 version. 

The repository has been cleaned of the bulk of the inline data resources.

### CODE REVIEW

**Comment by loleg** [comment]
```
oleg@localhost ~/L/g/swiss-maps> du -sh .
36M	.
```

**Comment by herrstucki** [comment]
Thanks @loleg!

The VEC200 files are usually part of the download you get from swisstopo directly. Not sure why they're not on opendata.swiss … so regarding deletion of data from the repo: I'm not sure if this is a good idea, since it's impossible to get those files from opendata.swiss (at least last time I checked).

Also, are you able to create the topojson files from this? I think those commands would also need to be updated 🤔 

Anyway, since this would change quite a bit and break compatibility with the older data, maybe it's better to create a fork that just fetches the latest data from opendata.swiss but isn't concerned with preserving older shapes. But I'm happy to discuss alternatives 😄

**Comment by loleg** [comment]
I'm cool with the idea of a separate branch / tag with historical data, but I don't think it warrants a separate fork of the repo. 

Re: topojson, I'll need to double check, but I believe my PR leads to a complete build.

One more thing: I've forked this into github.com/opendatach since (as discussed yesterday with open data practitioners in Bern), this repo definitely continues to be used, and should get more acknowledgement and support from the community.

**Comment by loleg** [comment]
I just ran `make` on a new machine, I could see the `topojson` commands executing without error, and the contents of the **build** folder are:
```
swiss-maps⟫ ls build
ag                               ge-municipalities-unmerged.json  so-municipalities.json
ag-lakes.json                    gl                               so-municipalities-unmerged.json
ag-lakes-unmerged.json           gl-lakes.json                    sz
ag-municipalities.json           gl-lakes-unmerged.json           sz-lakes.json
ag-municipalities-unmerged.json  gl-municipalities.json           sz-lakes-unmerged.json
ai                               gl-municipalities-unmerged.json  sz-municipalities.json
ai-municipalities.json           gr                               sz-municipalities-unmerged.json
ai-municipalities-unmerged.json  gr-municipalities.json           tg
ar                               gr-municipalities-unmerged.json  tg-lakes.json
ar-municipalities.json           ju                               tg-lakes-unmerged.json
ar-municipalities-unmerged.json  ju-municipalities.json           tg-municipalities.json
be                               ju-municipalities-unmerged.json  tg-municipalities-unmerged.json
be-lakes.json                    lu                               ti
be-lakes-unmerged.json           lu-lakes.json                    ti-lakes.json
be-municipalities.json           lu-lakes-unmerged.json           ti-lakes-unmerged.json
be-municipalities-unmerged.json  lu-municipalities.json           ti-municipalities.json
bl                               lu-municipalities-unmerged.json  ti-municipalities-unmerged.json
bl-municipalities.json           ne                               ur
bl-municipalities-unmerged.json  ne-lakes.json                    ur-lakes.json
bs                               ne-lakes-unmerged.json           ur-lakes-unmerged.json
bs-municipalities.json           ne-municipalities.json           ur-municipalities.json
bs-municipalities-unmerged.json  ne-municipalities-unmerged.json  ur-municipalities-unmerged.json
cantons.tsv                      nw                               vd
ch                               nw-lakes.json                    vd-lakes.json
ch-cantons.json                  nw-lakes-unmerged.json           vd-lakes-unmerged.json
ch-cantons-unmerged.json         nw-municipalities.json           vd-municipalities.json
ch-country.json                  nw-municipalities-unmerged.json  vd-municipalities-unmerged.json
ch-country-unmerged.json         ow                               vs
ch-districts.json                ow-lakes.json                    vs-lakes.json
ch-districts-unmerged.json       ow-lakes-unmerged.json           vs-lakes-unmerged.json
ch-lakes.json                    ow-municipalities.json           vs-municipalities.json
ch-lakes-unmerged.json           ow-municipalities-unmerged.json  vs-municipalities-unmerged.json
ch-municipalities.json           sg                               zg
ch-municipalities-unmerged.json  sg-lakes.json                    zg-lakes.json
fr                               sg-lakes-unmerged.json           zg-lakes-unmerged.json
fr-lakes.json                    sg-municipalities.json           zg-municipalities.json
fr-lakes-unmerged.json           sg-municipalities-unmerged.json  zg-municipalities-unmerged.json
fr-municipalities.json           sh                               zh
fr-municipalities-unmerged.json  sh-lakes.json                    zh-lakes.json
ge                               sh-lakes-unmerged.json           zh-lakes-unmerged.json
ge-lakes.json                    sh-municipalities.json           zh-municipalities.json
ge-lakes-unmerged.json           sh-municipalities-unmerged.json  zh-municipalities-unmerged.json
ge-municipalities.json           so
```

**Pull request closed without merging**
